# generated by datamodel-codegen

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from . import RpcStatus


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    hidden_types: Optional[list[str]] = Field(None, alias='hidden-types')
    """
    Types filtered and hidden at logger ouptut.
    """


class Output(BaseModel):
    class Config:
        allow_population_by_field_name = True

    message: Optional[str] = None
    """
    Information message about state of operation.
    """
    status: RpcStatus
