# generated by datamodel-codegen

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class TargetTransactions(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    transaction: Optional[list[str]] = None


class Input(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ignore_non_existing_nodes: Optional[bool] = Field(
        None, alias='ignore-non-existing-nodes'
    )
    """
    Controls whether to ignore non-existing target uniconfig nodes. By default, if the
    target-uuids-fields contains a transaction id for a non-existing node, then RPC fails.
    """
    target_transactions: Optional[TargetTransactions] = Field(
        None,
        alias='target-transactions',
        title='transaction.log.targetuuidsfields.TargetTransactions',
    )
