version: '3.8'

services:
  uniconfig-controller:
    user: root
    image: frinx/uniconfig:${IMAGE_TAG:?}
    entrypoint: ["sh", "-c", "cp /opt/uniconfig-frinx/openapi/uniconfig* /swagger"]
    volumes:
      - uniconfig_swagger:/swagger
      - uniconfig_swagger

  converter:
    build:
      context: .
    depends_on:
      uniconfig-controller:
        condition: service_completed_successfully
    entrypoint: 'sleep infinity'
    volumes:
      - .:/home/app
      - uniconfig_swagger:/swagger

volumes:
  uniconfig_swagger:
