#!/usr/bin/env bash

# remove obsolete files, because are not cleaned during generations
rm -rf /api/*

# generate pydantic classes from swagger
poetry run datamodel-codegen \
  --disable-timestamp \
  --enable-version-header \
  --use-schema-description \
  --use-field-description \
  --allow-population-by-field-name \
  --use-standard-collections \
  --openapi-scopes paths \
  --input /swagger/uniconfig.yaml \
  --output /api/ \
  --target-python-version 3.10 \
  --custom-file-header "#generated by datamodel-codegen"

chmod -R 777 /api/*

# generate rest_api file to map URL, Method and models from datamodel-codegen
poetry run python3 ./generate_rest_api.py --input /swagger/uniconfig.yaml --output /api/rest_api.py

# use default formatting
poetry run ruff --fix /api/rest_api.py || true
