# generated by datamodel-codegen

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class TypeOfPort(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    start_port: Optional[int] = Field(None, alias='start-port', ge=0, le=65535)
    end_port: Optional[int] = Field(None, alias='end-port', ge=0, le=65535)


class TypeOfPortModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    port: Optional[int] = Field(None, ge=0, le=65535)


class TcpPortItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type_of_port: Optional[Union[TypeOfPort, TypeOfPortModel]] = Field(
        None, alias='type-of-port'
    )


class TypeOfAddress(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    hostname: Optional[str] = None
    """
    Domain name
    """


class TypeOfAddressModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ip_address: Optional[str] = Field(None, alias='ip-address')
    """
    IP address in either IPv4 or IPv6 format, the syntax
    then determines which version is used
    """


class TypeOfAddressModel1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    start_ipv4_address: Optional[str] = Field(None, alias='start-ipv4-address')
    end_ipv4_address: Optional[str] = Field(None, alias='end-ipv4-address')


class TypeOfAddressModel2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    start_ipv6_address: Optional[str] = Field(None, alias='start-ipv6-address')
    end_ipv6_address: Optional[str] = Field(None, alias='end-ipv6-address')


class TypeOfAddressModel3(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    network: Optional[str] = None
    """
    IP address with a subnet mask either in IPv4 or IPv6 format,
    the syntax then determines which version is used
    """


class Addres(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type_of_address: Optional[
        Union[
            TypeOfAddress,
            TypeOfAddressModel,
            TypeOfAddressModel1,
            TypeOfAddressModel2,
            TypeOfAddressModel3,
        ]
    ] = Field(None, alias='type-of-address')


class TypeOfPortModel1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    start_port: Optional[int] = Field(None, alias='start-port', ge=0, le=65535)
    end_port: Optional[int] = Field(None, alias='end-port', ge=0, le=65535)


class TypeOfPortModel2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    port: Optional[int] = Field(None, ge=0, le=65535)


class UdpPortItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type_of_port: Optional[Union[TypeOfPortModel1, TypeOfPortModel2]] = Field(
        None, alias='type-of-port'
    )


class Input(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    verify_host_reachability: Optional[bool] = Field(
        None, alias='verify-host-reachability'
    )
    """
    Check whether the host is reachable or not using ICMP protocol
    """
    tcp_port: Optional[list[TcpPortItem]] = Field(None, alias='tcp-port')
    address: Optional[list[Addres]] = None
    udp_port: Optional[list[UdpPortItem]] = Field(None, alias='udp-port')


class DeviceItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    host: Optional[str] = None
    """
    Host address either in IP (IPv4 or IPv6) format or in domain-name format
    """
    unavailable_tcp_ports: Optional[list[int]] = Field(
        None, alias='unavailable-tcp-ports', ge=0, le=65535
    )
    """
    TCP ports that are unreachable
    """
    is_host_reachable: Optional[bool] = Field(None, alias='is-host-reachable')
    """
    If the host is reachable or not using ICMP protocol
    """
    available_tcp_ports: Optional[list[int]] = Field(
        None, alias='available-tcp-ports', ge=0, le=65535
    )
    """
    All the available TCP ports
    """
    unavailable_udp_ports: Optional[list[int]] = Field(
        None, alias='unavailable-udp-ports', ge=0, le=65535
    )
    """
    UDP ports that are unreachable
    """
    available_udp_ports: Optional[list[int]] = Field(
        None, alias='available-udp-ports', ge=0, le=65535
    )
    """
    All the available UDP ports
    """


class Output(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    device: Optional[list[DeviceItem]] = None
