# generated by datamodel-codegen

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from . import RepositoryCreationStatus


class Input(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    repository_name: Optional[str] = Field(None, alias='repository-name')
    """
    Name of the schema repository / directory that is used for persistence of YANG artifacts.
    """


class Output(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    error_message: Optional[str] = Field(None, alias='error-message')
    """
    The cause of the failure.
    """
    status: RepositoryCreationStatus
