# generated by datamodel-codegen

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field


class TargetNodes(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    node: Optional[list[str]] = None


class Input(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    check_timestamp: Optional[bool] = Field(None, alias='check-timestamp')
    """
    Perform timestamp comparison(last known to Uniconfig vs current timestamp on device)
    before loading all configuration from a device.
    """
    target_nodes: Optional[TargetNodes] = Field(
        None,
        alias='target-nodes',
        title='uniconfig.manager.targetuniconfigunistorenodesfields.TargetNodes',
    )


class DeletedDatum(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[str] = None
    path: Optional[str] = None
    """
    Instance-identifier of deleted data node.
    """


class CreatedDatum(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[str] = None
    path: Optional[str] = None
    """
    Instance-identifier of created data node.
    """


class UpdatedDatum(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    path: Optional[str] = None
    """
    Instance-identifier of updated data node.
    """
    data_intended: Optional[str] = Field(None, alias='data-intended')
    data_actual: Optional[str] = Field(None, alias='data-actual')


class ReorderedList(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    path: Optional[str] = None
    """
    Instance-identifier of reordered list.
    """
    actual_list_keys: Optional[str] = Field(None, alias='actual-list-keys')
    intended_list_keys: Optional[str] = Field(None, alias='intended-list-keys')


class NodeResultItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    deleted_data: Optional[list[DeletedDatum]] = Field(None, alias='deleted-data')
    """
    Removed intended configuration against actual.
    """
    node_id: Optional[str] = Field(None, alias='node-id')
    created_data: Optional[list[CreatedDatum]] = Field(None, alias='created-data')
    """
    Created intended configuration against actual.
    """
    topology_id: Optional[str] = Field(None, alias='topology-id')
    updated_data: Optional[list[UpdatedDatum]] = Field(None, alias='updated-data')
    """
    Updated intended configuration against actual.
    """
    reordered_lists: Optional[list[ReorderedList]] = Field(
        None, alias='reordered-lists'
    )
    """
    Reordered intended list against actual.
    """


class NodeResults(BaseModel):
    """
    Individual result of configuration comparison for given nodes.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    node_result: Optional[list[NodeResultItem]] = Field(None, alias='node-result')
    """
    Differences between intended and actual uniconfig node.
    """


class Output(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    node_results: Optional[NodeResults] = Field(
        None,
        alias='node-results',
        title='uniconfig.manager.compareconfigoutputfields.NodeResults',
    )
    """
    Individual result of configuration comparison for given nodes.
    """
