# generated by datamodel-codegen

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class TargetNodes(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    node: Optional[list[str]] = None


class Input(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    target_nodes: Optional[TargetNodes] = Field(
        None,
        alias='target-nodes',
        title='uniconfig.manager.targetuniconfignodesfields.TargetNodes',
    )


class NodeResultItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    node_id: Optional[str] = Field(None, alias='node-id')
    is_in_sync: Optional[bool] = Field(None, alias='is-in-sync')


class NodeResults(BaseModel):
    """
    Result of checking if network elements are in-sync with operational datastore.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    node_result: Optional[list[NodeResultItem]] = Field(None, alias='node-result')
    """
    Result of is-in-sync operation on the given node.
    """


class Output(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    node_results: Optional[NodeResults] = Field(
        None,
        alias='node-results',
        title='uniconfig.manager.isinsyncoutputfields.NodeResults',
    )
    """
    Result of checking if network elements are in-sync with operational datastore.
    """
