# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2024-12-02T11:12:29+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional, TypeAlias

from pydantic import BaseModel, Field

Boolean: TypeAlias = bool
"""
The `Boolean` scalar type represents `true` or `false`.
"""


Float: TypeAlias = float
"""
The `Float` scalar type represents signed double-precision fractional values as specified by [IEEE 754](https://en.wikipedia.org/wiki/IEEE_floating_point).
"""


ID: TypeAlias = str
"""
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
"""


Int: TypeAlias = int
"""
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
"""


JSON: TypeAlias = str
"""
JSON document.
"""


String: TypeAlias = str
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


class BgpLsProtocolType(Enum):
    """
    BGP-LS Protocol types.
    """

    isis = 'ISIS'
    ospf = 'OSPF'


class CoordinatesNodeType(Enum):
    """
    Type of the node in the topology for which the coordinates are being updated.
    """

    device = 'DEVICE'
    network = 'NETWORK'


class GeometryType(Enum):
    """
    Type of geometry.
    """

    point = 'POINT'


class MplsOperation(Enum):
    noop = 'NOOP'
    pop = 'POP'
    push = 'PUSH'
    swap = 'SWAP'


class NetRoutingPathOutputCollections(Enum):
    """
    Types of the nodes that should be included in the returned path.
    """

    net_device = 'NET_DEVICE'
    net_interface = 'NET_INTERFACE'


class NodeStatus(Enum):
    """
    Status of the node from the view of the device registry.
    """

    ok = 'OK'
    unknown = 'UNKNOWN'


class PtpPathOutputCollections(Enum):
    """
    Types of the nodes that should be included in the returned path.
    """

    ptp_device = 'PTP_DEVICE'
    ptp_interface = 'PTP_INTERFACE'


class Signalisation(Enum):
    ldp = 'LDP'
    rsvp = 'RSVP'


class SyncePathOutputCollections(Enum):
    """
    Types of the nodes that should be included in the returned path.
    """

    synce_device = 'SYNCE_DEVICE'
    synce_interface = 'SYNCE_INTERFACE'


class TopologyType(Enum):
    """
    Present topology types.
    """

    eth_topology = 'ETH_TOPOLOGY'
    mpls_topology = 'MPLS_TOPOLOGY'
    network_topology = 'NETWORK_TOPOLOGY'
    physical_topology = 'PHYSICAL_TOPOLOGY'
    ptp_topology = 'PTP_TOPOLOGY'


class Node(BaseModel):
    """
    Generic node that can be identified using Globally Unique ID.
    """

    id: ID = Field(..., description='Unique identifier of the object.')
    typename__: Optional[Literal['Node']] = Field('Node', alias='__typename')


class CommonNodesResponse(BaseModel):
    """
    Response from the commonNodes query that wraps the list of found common nodes in the database.
    """

    common_nodes: List[String] = Field(
        ...,
        alias='commonNodes',
        description='List of the common node names. Common nodes contain connection to all nodes specified on the input.',
    )
    typename__: Optional[Literal['CommonNodesResponse']] = Field(
        'CommonNodesResponse', alias='__typename'
    )


class Coordinates(BaseModel):
    """
    Coordinates of the node on the graph.
    """

    x: Float = Field(..., description='Horizontal coordinate of the node on the graph.')
    y: Float = Field(..., description='Vertical coordinate of the node on the graph.')
    typename__: Optional[Literal['Coordinates']] = Field(
        'Coordinates', alias='__typename'
    )


class CoordinatesResponse(BaseModel):
    """
    Response from the updateCoordinates query that contains information about updated coordinated of selected nodes.
    """

    installed: InstalledDevices = Field(
        ..., description='Devices that exist in the database.'
    )
    not_installed: List[String] = Field(
        ...,
        alias='notInstalled',
        description='List of node names that do not exist in the database.',
    )
    typename__: Optional[Literal['CoordinatesResponse']] = Field(
        'CoordinatesResponse', alias='__typename'
    )


class CreateBackupResponse(BaseModel):
    """
    Response from the createBackup mutation that contains information about created backup.
    """

    db_name: String = Field(
        ...,
        alias='dbName',
        description='Name of the created backup database. Format: f"backup_{datetime.today().strftime(\'%Y%m%d%H%M%S\')}".',
    )
    typename__: Optional[Literal['CreateBackupResponse']] = Field(
        'CreateBackupResponse', alias='__typename'
    )


class DeleteBackupsResponse(BaseModel):
    """
    Response from the deleteBackups mutation that contains information about removed backups.
    """

    deleted_backups: List[String] = Field(
        ...,
        alias='deletedBackups',
        description='Names of the removed databases that contained backups.',
    )
    typename__: Optional[Literal['DeleteBackupsResponse']] = Field(
        'DeleteBackupsResponse', alias='__typename'
    )


class DeviceGeoLocation(BaseModel):
    """
    Device GeoLocation data.
    """

    bbox: Optional[List[Optional[Float]]] = Field(
        None,
        description='Defining the area around the device, with four elements indicating its boundaries.',
    )
    coordinates: List[Float] = Field(
        ...,
        description='Device location coordinates providing longitude and latitude (in this order, based on GeoJSON convention).',
    )
    type: GeometryType = Field(..., description='Type of geometry.')
    typename__: Optional[Literal['DeviceGeoLocation']] = Field(
        'DeviceGeoLocation', alias='__typename'
    )


class DeviceMetadata(Node):
    """
    Representation of the device in the metadata.
    """

    device_name: String = Field(
        ..., alias='deviceName', description='Human readable name of the device.'
    )
    device_type: Optional[String] = Field(
        None, alias='deviceType', description='Type of the device (ex. router).'
    )
    geo_location: Optional[DeviceGeoLocation] = Field(
        None,
        alias='geoLocation',
        description='Device geographic data of point type in GeoJson format.',
    )
    id: ID = Field(..., description='Unique identifier of the object.')
    model: Optional[String] = Field(None, description='Model of the device (XR, ASR).')
    protocol_type: Optional[List[String]] = Field(
        None,
        alias='protocolType',
        description='Protocol used for management for the device (cli, netconf, gnmi).',
    )
    vendor: Optional[String] = Field(
        None, description='Vendor of the device (ex. Cisco).'
    )
    version: Optional[String] = Field(
        None, description='Version of the device software (ex. 6.0.1).'
    )
    typename__: Optional[Literal['DeviceMetadata']] = Field(
        'DeviceMetadata', alias='__typename'
    )


class DeviceMetadataEdge(BaseModel):
    """
    Grouped Metadata device object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    node: Optional[DeviceMetadata] = Field(
        None, description='The associated MetadataDevice object.'
    )
    typename__: Optional[Literal['DeviceMetadataEdge']] = Field(
        'DeviceMetadataEdge', alias='__typename'
    )


class InstalledDevices(BaseModel):
    not_updated: List[String] = Field(
        ...,
        alias='notUpdated',
        description='List of node names which coordinates have not been updated.',
    )
    updated: List[String] = Field(
        ..., description='List of node names which coordinates have been updated.'
    )
    typename__: Optional[Literal['InstalledDevices']] = Field(
        'InstalledDevices', alias='__typename'
    )


class LspTunnel(BaseModel):
    """
    LSP Tunnel (related to tunnel originating from this device).
    """

    from_device: Optional[String] = Field(
        None,
        alias='fromDevice',
        description='From which device is the tunnel originating.',
    )
    lsp_id: String = Field(
        ..., alias='lspId', description='Name of the link state packet.'
    )
    signalisation: Signalisation = Field(..., description='Type of signalisation.')
    to_device: Optional[String] = Field(
        None, alias='toDevice', description='Where is the tunnel headed.'
    )
    uptime: Optional[Int] = Field(None, description='Uptime of the tunnel in seconds.')
    typename__: Optional[Literal['LspTunnel']] = Field('LspTunnel', alias='__typename')


class MetadataConnection(BaseModel):
    """
    Grouped list of Metadata device objects and pagination metadata.
    """

    edges: Optional[List[Optional[DeviceMetadataEdge]]] = Field(
        None, description='List of Metadata device objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['MetadataConnection']] = Field(
        'MetadataConnection', alias='__typename'
    )


class MplsData(BaseModel):
    """
    MPLS Data (related to all tunnels).
    """

    in_interface: Optional[String] = Field(
        None, alias='inInterface', description='The input interface.'
    )
    in_label: Optional[Int] = Field(
        None, alias='inLabel', description='The input label.'
    )
    lsp_id: String = Field(
        ..., alias='lspId', description='Name of the link state packet.'
    )
    mpls_operation: Optional[MplsOperation] = Field(
        None, alias='mplsOperation', description='The operation type.'
    )
    oper_state: Optional[String] = Field(
        None, alias='operState', description='Operational state of the device.'
    )
    out_interface: Optional[String] = Field(
        None, alias='outInterface', description='The input interface.'
    )
    out_label: Optional[Int] = Field(
        None, alias='outLabel', description='The output label.'
    )
    signalisation: Optional[Signalisation] = Field(
        None, description='Type of signalisation.'
    )
    typename__: Optional[Literal['MplsData']] = Field('MplsData', alias='__typename')


class MplsDevice(Node):
    """
    Representation of the device in the MPLS topology.
    """

    coordinates: Coordinates = Field(
        ..., description='Coordinates of the device node on the graph.'
    )
    details: MplsDeviceDetails = Field(..., description='Details of the device.')
    id: ID = Field(..., description='Unique identifier of the object.')
    labels: Optional[List[String]] = Field(
        None,
        description='List of strings that can be used for grouping of synced devices.',
    )
    mpls_interfaces: MplsInterfaceConnection = Field(
        ...,
        alias='mplsInterfaces',
        description='List of ports that are present on the device.',
    )
    name: String = Field(..., description='Human readable name of the device.')
    status: NodeStatus = Field(
        ..., description='Status of the device from the view of the synced topology.'
    )
    typename__: Optional[Literal['MplsDevice']] = Field(
        'MplsDevice', alias='__typename'
    )


class MplsDeviceConnection(BaseModel):
    """
    Grouped list of MplsDevice objects and pagination metadata.
    """

    edges: Optional[List[Optional[MplsDeviceEdge]]] = Field(
        None, description='List of MplsDevice objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['MplsDeviceConnection']] = Field(
        'MplsDeviceConnection', alias='__typename'
    )


class MplsDeviceDetails(BaseModel):
    """
    Details specific to MPLS (Multi-Protocol Label Switching).
    """

    lsp_tunnels: Optional[List[Optional[LspTunnel]]] = Field(None, alias='lspTunnels')
    mpls_data: Optional[List[Optional[MplsData]]] = Field(None, alias='mplsData')
    router_id: Optional[String] = Field(None, alias='routerId')
    typename__: Optional[Literal['MplsDeviceDetails']] = Field(
        'MplsDeviceDetails', alias='__typename'
    )


class MplsDeviceEdge(BaseModel):
    """
    Grouped MplsDevice object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    node: Optional[MplsDevice] = Field(
        None, description='The associated MplsDevice object.'
    )
    typename__: Optional[Literal['MplsDeviceEdge']] = Field(
        'MplsDeviceEdge', alias='__typename'
    )


class MplsInterface(Node):
    """
    Port attached to the MPLS device.
    """

    id: ID = Field(..., description='Unique identifier of the object.')
    mpls_device: Optional[MplsDevice] = Field(
        None, alias='mplsDevice', description='Device that owns this interface.'
    )
    mpls_links: Optional[MplsLinkConnection] = Field(
        None, alias='mplsLinks', description='Link to connected remote MPLS device.'
    )
    name: String = Field(..., description='Human readable name of the network port.')
    status: NodeStatus = Field(
        ...,
        description="Status of the interface from the view of the synced topology ('ok' or 'unknown').",
    )
    typename__: Optional[Literal['MplsInterface']] = Field(
        'MplsInterface', alias='__typename'
    )


class MplsInterfaceConnection(BaseModel):
    """
    Grouped list of MplsInterface objects and pagination metadata.
    """

    edges: Optional[List[Optional[MplsInterfaceEdge]]] = Field(
        None, description='List of MplsInterface objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['MplsInterfaceConnection']] = Field(
        'MplsInterfaceConnection', alias='__typename'
    )


class MplsInterfaceEdge(BaseModel):
    """
    Grouped MplsInterface object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    node: Optional[MplsInterface] = Field(
        None, description='The associated MplsInterface object.'
    )
    typename__: Optional[Literal['MplsInterfaceEdge']] = Field(
        'MplsInterfaceEdge', alias='__typename'
    )


class MplsLinkConnection(BaseModel):
    """
    Grouped list of MplsLinks objects and pagination metadata.
    """

    edges: Optional[List[Optional[MplsLinkEdge]]] = Field(
        None, description='List of MplsInterface objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['MplsLinkConnection']] = Field(
        'MplsLinkConnection', alias='__typename'
    )


class MplsLinkEdge(BaseModel):
    """
    Grouped MplsLink object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    link: Optional[ID] = Field(
        None,
        description='Identifier of the link that connects this interface to the interface on the remote device',
    )
    node: Optional[MplsInterface] = Field(
        None, description='The associated MplsInterface object.'
    )
    typename__: Optional[Literal['MplsLinkEdge']] = Field(
        'MplsLinkEdge', alias='__typename'
    )


class MplsLspMetadata(BaseModel):
    from_device: String = Field(
        ...,
        alias='fromDevice',
        description='From which device is the tunnel originating.',
    )
    signalisation: String = Field(..., description='Type of signalisation.')
    to_device: String = Field(
        ..., alias='toDevice', description='Where is the tunnel headed.'
    )
    uptime: Optional[Int] = Field(None, description='Uptime of the tunnel in seconds.')
    typename__: Optional[Literal['MplsLspMetadata']] = Field(
        'MplsLspMetadata', alias='__typename'
    )


class MplsLspPath(BaseModel):
    lsp_metadata: Optional[MplsLspMetadata] = Field(
        None, alias='lspMetadata', description='LSP metadata.'
    )
    path: Optional[List[Optional[String]]] = Field(
        None, description='Ordered list of link IDs & device IDs on the path.'
    )
    typename__: Optional[Literal['MplsLspPath']] = Field(
        'MplsLspPath', alias='__typename'
    )


class MplsTotalLsps(BaseModel):
    incoming_lsps: Optional[Int] = Field(
        None, alias='incomingLsps', description='Number of incoming LSPs.'
    )
    outcoming_lsps: Optional[Int] = Field(
        None, alias='outcomingLsps', description='Number of outcoming LSPs.'
    )
    to_device: Optional[String] = Field(
        None, alias='toDevice', description='To which device the LSP is headed.'
    )
    typename__: Optional[Literal['MplsTotalLsps']] = Field(
        'MplsTotalLsps', alias='__typename'
    )


class Neighbor(BaseModel):
    """
    Metadata information about a neighbor device.
    """

    device_id: String = Field(
        ...,
        alias='deviceId',
        description='Identifier of the neighbor device document (for example, MplsDevice/1).',
    )
    device_name: String = Field(
        ...,
        alias='deviceName',
        description='Human-readable name of the neighbor device (for example, CPE_01).',
    )
    typename__: Optional[Literal['Neighbor']] = Field('Neighbor', alias='__typename')


class NetDevice(Node):
    """
    Representation of the routing entity in the network topology.
    """

    coordinates: Coordinates = Field(
        ..., description='Coordinates of the device node on the graph.'
    )
    id: ID = Field(..., description='Unique identifier of the object.')
    net_interfaces: NetInterfaceConnection = Field(
        ...,
        alias='netInterfaces',
        description='Interfaces that are used for connecting to other routing entities.',
    )
    net_networks: NetNetworkConnection = Field(
        ...,
        alias='netNetworks',
        description='Networks that are attached to the routing entity.',
    )
    ospf_area_id: String = Field(
        ...,
        alias='ospfAreaId',
        description='Identifier of OSPF area formatted as IPv4 address (for example, 0.0.0.0 represents area 0).',
    )
    phy_device: Optional[PhyDevice] = Field(
        None, alias='phyDevice', description='Linked device in the physical topology.'
    )
    router_id: String = Field(
        ...,
        alias='routerId',
        description='Identifier of the routing entity (usually IPv4 address). RouterId and ospfAreaId together compose a unique key.',
    )
    typename__: Optional[Literal['NetDevice']] = Field('NetDevice', alias='__typename')


class NetDeviceConnection(BaseModel):
    """
    Grouped list of NetDevice objects and pagination metadata.
    """

    edges: Optional[List[Optional[NetDeviceEdge]]] = Field(
        None, description='List of NetDevice objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['NetDeviceConnection']] = Field(
        'NetDeviceConnection', alias='__typename'
    )


class NetDeviceEdge(BaseModel):
    """
    Grouped NetDevice object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    node: Optional[NetDevice] = Field(
        None, description='The associated NetDevice object.'
    )
    typename__: Optional[Literal['NetDeviceEdge']] = Field(
        'NetDeviceEdge', alias='__typename'
    )


class NetInterface(Node):
    """
    Network interface attached to the network device.
    """

    id: ID = Field(..., description='Unique identifier of the object.')
    igp_metric: Optional[Int] = Field(
        None,
        alias='igpMetric',
        description='IGP metric configured on the network interface.',
    )
    ip_address: String = Field(
        ..., alias='ipAddress', description='IP address configured on the interface.'
    )
    net_device: Optional[NetDevice] = Field(
        None, alias='netDevice', description='Routing entity that owns this interface.'
    )
    net_links: NetLinkConnection = Field(
        ..., alias='netLinks', description='Links to connected remote network devices.'
    )
    typename__: Optional[Literal['NetInterface']] = Field(
        'NetInterface', alias='__typename'
    )


class NetInterfaceConnection(BaseModel):
    """
    Grouped list of NetInterface objects and pagination metadata.
    """

    edges: Optional[List[Optional[NetInterfaceEdge]]] = Field(
        None, description='List of NetInterface objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['NetInterfaceConnection']] = Field(
        'NetInterfaceConnection', alias='__typename'
    )


class NetInterfaceEdge(BaseModel):
    """
    Grouped NetInterface object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    node: Optional[NetInterface] = Field(
        None, description='The associated NetInterface object.'
    )
    typename__: Optional[Literal['NetInterfaceEdge']] = Field(
        'NetInterfaceEdge', alias='__typename'
    )


class NetLinkAttributes(BaseModel):
    admin_group: Optional[List[Optional[Int]]] = Field(
        None,
        alias='adminGroup',
        description='A list of admin group masks on the network interface. (Group Number)',
    )
    igp_metric: Optional[Int] = Field(
        None,
        alias='igpMetric',
        description='IGP metric configured on the network interface.',
    )
    max_link_bandwidth: Optional[Float] = Field(
        None,
        alias='maxLinkBandwidth',
        description='The maximum link bandwidth of the network interface. (Bytes per second)',
    )
    max_reservable_link_bandwidth: Optional[Float] = Field(
        None,
        alias='maxReservableLinkBandwidth',
        description='The maximum reservable link bandwidth of the network interface. (Bytes per second)',
    )
    shared_risk_link_group: Optional[List[Optional[Int]]] = Field(
        None,
        alias='sharedRiskLinkGroup',
        description='A list of shared risk link groups on the network interface.',
    )
    traffic_engineering_metric: Optional[Int] = Field(
        None,
        alias='trafficEngineeringMetric',
        description='Traffic Engineering metric on the network interface.',
    )
    unreserved_bandwidth: Optional[List[Optional[Float]]] = Field(
        None,
        alias='unreservedBandwidth',
        description='The unreserved bandwidth on the network interface. (Bytes per second)',
    )
    typename__: Optional[Literal['NetLinkAttributes']] = Field(
        'NetLinkAttributes', alias='__typename'
    )


class NetLinkConnection(BaseModel):
    """
    Grouped list of NetLinks objects and pagination metadata.
    """

    edges: Optional[List[Optional[NetLinkEdge]]] = Field(
        None, description='List of NetInterface objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['NetLinkConnection']] = Field(
        'NetLinkConnection', alias='__typename'
    )


class NetLinkEdge(BaseModel):
    attributes: Optional[NetLinkAttributes] = Field(
        None, description='List of attributes associated to the link.'
    )
    cursor: String = Field(..., description='Pagination cursor for this edge.')
    link: Optional[ID] = Field(
        None,
        description='Identifier of the link that connects this interface to the interface on the remote device',
    )
    node: Optional[NetInterface] = Field(
        None, description='The associated NetInterface object.'
    )
    typename__: Optional[Literal['NetLinkEdge']] = Field(
        'NetLinkEdge', alias='__typename'
    )


class NetNetwork(Node):
    """
    IP subnet in the network topology.
    """

    coordinates: Coordinates = Field(
        ..., description='Coordinates of the network node on the graph.'
    )
    id: ID = Field(..., description='Unique identifier of the object.')
    ospf_route_type: Int = Field(
        ..., alias='ospfRouteType', description='Type of the OSPF network (LSA type).'
    )
    subnet: String = Field(
        ...,
        description='Network address including prefix length expressed in the CIDR notation (e.g. 10.0.0.0/24).',
    )
    typename__: Optional[Literal['NetNetwork']] = Field(
        'NetNetwork', alias='__typename'
    )


class NetNetworkConnection(BaseModel):
    """
    Grouped list of NetNetwork objects and pagination metadata.
    """

    edges: Optional[List[Optional[NetNetworkEdge]]] = Field(
        None, description='List of NetNetwork objects.'
    )
    page_info: Optional[PageInfo] = Field(
        None, alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['NetNetworkConnection']] = Field(
        'NetNetworkConnection', alias='__typename'
    )


class NetNetworkEdge(BaseModel):
    cursor: String = Field(..., description='Pagination cursor for this edge.')
    node: Optional[NetNetwork] = Field(
        None, description='The associated NetNetwork object.'
    )
    typename__: Optional[Literal['NetNetworkEdge']] = Field(
        'NetNetworkEdge', alias='__typename'
    )


class NetRoutingPathConnection(BaseModel):
    """
    Computed routing paths from source to destination device.
    """

    edges: Optional[List[RoutingPath]] = Field(
        None,
        description='List of routing paths from source to destination device. Ordered from shortest to longest path based on weight.',
    )
    typename__: Optional[Literal['NetRoutingPathConnection']] = Field(
        'NetRoutingPathConnection', alias='__typename'
    )


class NodeCoordinates(BaseModel):
    """
    Represents the coordinates of a specific node in the topology.
    """

    node_id: String = Field(
        ..., alias='nodeId', description='Name of the node in the topology.'
    )
    x: Float = Field(
        ...,
        description='Refreshed horizontal coordinate of the node on the graph. Value is between 0.0 and 1.0.',
    )
    y: Float = Field(
        ...,
        description='Refreshed vertical coordinate of the node on the graph. Value is between 0.0 and 1.0.',
    )
    typename__: Optional[Literal['NodeCoordinates']] = Field(
        'NodeCoordinates', alias='__typename'
    )


class NodeInfo(BaseModel):
    """
    Information about a node that is part of the computed path.
    """

    node: ID = Field(..., description='Unique identifier of the node on the path.')
    weight: Optional[Int] = Field(
        None,
        description='Weight of the node on the path. Weight is present only on the nodes of NetDevice type.',
    )
    typename__: Optional[Literal['NodeInfo']] = Field('NodeInfo', alias='__typename')


class PageInfo(BaseModel):
    """
    Pagination metadata that is usually coupled to a returned list of objects.
    """

    end_cursor: Optional[String] = Field(
        None, alias='endCursor', description='Pointer to the last object in the list.'
    )
    has_next_page: Boolean = Field(
        ...,
        alias='hasNextPage',
        description='Indicates if there is a next object in the list.',
    )
    typename__: Optional[Literal['PageInfo']] = Field('PageInfo', alias='__typename')


class PhyDevice(Node):
    """
    Representation of the device in the physical topology.
    """

    coordinates: Coordinates = Field(
        ..., description='Coordinates of the device node on the graph.'
    )
    details: PhyDeviceDetails = Field(..., description='Details of the device.')
    id: ID = Field(..., description='Unique identifier of the object.')
    labels: Optional[List[String]] = Field(
        None,
        description='List of strings that can be used for grouping of synced devices.',
    )
    name: String = Field(..., description='Human readable name of the device.')
    net_device: Optional[NetDevice] = Field(
        None, alias='netDevice', description='Linked device in the network topology.'
    )
    phy_interfaces: PhyInterfaceConnection = Field(
        ...,
        alias='phyInterfaces',
        description='List of ports that are present on the device.',
    )
    router_id: Optional[String] = Field(
        None,
        alias='routerId',
        description='Identifier of the corresponding routing entity in the network topology.',
    )
    status: NodeStatus = Field(
        ..., description='Status of the device from the view of the synced topology.'
    )
    typename__: Optional[Literal['PhyDevice']] = Field('PhyDevice', alias='__typename')


class PhyDeviceConnection(BaseModel):
    """
    Grouped list of PhyDevice objects and pagination metadata.
    """

    edges: Optional[List[Optional[PhyDeviceEdge]]] = Field(
        None, description='List of PhyDevice objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['PhyDeviceConnection']] = Field(
        'PhyDeviceConnection', alias='__typename'
    )


class PhyDeviceDetails(BaseModel):
    """
    Details of the device.
    """

    device_type: Optional[String] = Field(
        None,
        alias='deviceType',
        description='Device type (e.g. device model, vendor, chassis, hardware details, etc.)',
    )
    sw_version: Optional[String] = Field(
        None,
        alias='swVersion',
        description='Version of the network operating system running on the device.',
    )
    typename__: Optional[Literal['PhyDeviceDetails']] = Field(
        'PhyDeviceDetails', alias='__typename'
    )


class PhyDeviceEdge(BaseModel):
    """
    Grouped PhyDevice object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    node: Optional[PhyDevice] = Field(
        None, description='The associated PhyDevice object.'
    )
    typename__: Optional[Literal['PhyDeviceEdge']] = Field(
        'PhyDeviceEdge', alias='__typename'
    )


class PhyInterface(Node):
    """
    Port attached to the physical device.
    """

    details: Optional[PhyInterfaceDetails] = Field(
        None, description='Details of the interface.'
    )
    id: ID = Field(..., description='Unique identifier of the object.')
    name: String = Field(..., description='Human readable name of the network port.')
    phy_device: Optional[PhyDevice] = Field(
        None, alias='phyDevice', description='Device that owns this interface.'
    )
    phy_links: PhyLinkConnection = Field(
        ...,
        alias='phyLinks',
        description='List of links connected to remote physical device.',
    )
    status: NodeStatus = Field(
        ...,
        description="Status of the interface from the view of the synced topology ('ok' or 'unknown').",
    )
    typename__: Optional[Literal['PhyInterface']] = Field(
        'PhyInterface', alias='__typename'
    )


class PhyInterfaceConnection(BaseModel):
    """
    Grouped list of PhyInterface objects and pagination metadata.
    """

    edges: Optional[List[Optional[PhyInterfaceEdge]]] = Field(
        None, description='List of PhyInterface objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['PhyInterfaceConnection']] = Field(
        'PhyInterfaceConnection', alias='__typename'
    )


class PhyInterfaceDetails(BaseModel):
    """
    Details of the interface.
    """

    max_speed: Optional[Float] = Field(
        None,
        alias='maxSpeed',
        description='Max operational interface bandwidth in Mbit.',
    )
    typename__: Optional[Literal['PhyInterfaceDetails']] = Field(
        'PhyInterfaceDetails', alias='__typename'
    )


class PhyInterfaceEdge(BaseModel):
    """
    Grouped PhyInterface object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    node: Optional[PhyInterface] = Field(
        None, description='The associated PhyInterface object.'
    )
    typename__: Optional[Literal['PhyInterfaceEdge']] = Field(
        'PhyInterfaceEdge', alias='__typename'
    )


class PhyLinkConnection(BaseModel):
    """
    Grouped list of PhyLinks objects and pagination metadata.
    """

    edges: Optional[List[Optional[PhyLinkEdge]]] = Field(
        None, description='List of PhyInterface objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['PhyLinkConnection']] = Field(
        'PhyLinkConnection', alias='__typename'
    )


class PhyLinkEdge(BaseModel):
    cursor: String = Field(..., description='Pagination cursor for this edge.')
    link: Optional[ID] = Field(
        None,
        description='Identifier of the link that connects this interface to the interface on the remote device',
    )
    node: Optional[PhyInterface] = Field(
        None, description='The associated PhyInterface object.'
    )
    typename__: Optional[Literal['PhyLinkEdge']] = Field(
        'PhyLinkEdge', alias='__typename'
    )


class ProviderResponse(BaseModel):
    """
    Response from the provider query that contains information about supported device types in the specified topology.
    """

    supported_devices: List[String] = Field(
        ...,
        alias='supportedDevices',
        description='List of the supported device types in the specified topology (e.g. ios, ios xe, sros, etc.)',
    )
    typename__: Optional[Literal['ProviderResponse']] = Field(
        'ProviderResponse', alias='__typename'
    )


class PtpDevice(Node):
    """
    Representation of the device in the ptp topology.
    """

    coordinates: Coordinates = Field(
        ..., description='Coordinates of the device node on the graph.'
    )
    details: PtpDeviceDetails = Field(..., description='Details of the device.')
    id: ID = Field(..., description='Unique identifier of the object.')
    labels: Optional[List[String]] = Field(
        None,
        description='List of strings that can be used for grouping of synced devices.',
    )
    name: String = Field(..., description='Human readable name of the device.')
    ptp_interfaces: PtpInterfaceConnection = Field(
        ...,
        alias='ptpInterfaces',
        description='List of ports that are present on the device.',
    )
    status: NodeStatus = Field(
        ..., description='Status of the device from the view of the synced topology.'
    )
    typename__: Optional[Literal['PtpDevice']] = Field('PtpDevice', alias='__typename')


class PtpDeviceConnection(BaseModel):
    """
    Grouped list of PtpDevice objects and pagination metadata.
    """

    edges: Optional[List[Optional[PtpDeviceEdge]]] = Field(
        None, description='List of PtpDevice objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['PtpDeviceConnection']] = Field(
        'PtpDeviceConnection', alias='__typename'
    )


class PtpDeviceDetails(BaseModel):
    """
    Details specific to PTP (Precision Time Protocol).
    """

    clock_accuracy: Optional[String] = Field(
        None,
        alias='clockAccuracy',
        description='How accurate is the clock output to primary reference. This parameter is often automatically determined\nby the device based on the characteristics of its internal clock oscillator and how well it can track\nthe reference time.',
    )
    clock_class: Optional[Int] = Field(
        None, alias='clockClass', description='Measure of clock traceability.'
    )
    clock_id: Optional[String] = Field(
        None, alias='clockId', description='Unique identifier of the clock.'
    )
    clock_type: Optional[String] = Field(
        None, alias='clockType', description='Type of clock (e.g., ordinary, master).'
    )
    clock_variance: Optional[String] = Field(
        None,
        alias='clockVariance',
        description="Measure of clock precision. How much the clock-output varies when not synchronized to another source.\nThe variance is determined by assessing how much the local clock deviates from the ideal time over a certain period,\noften expressed in parts per billion (ppb) or as the standard deviation of the clock's offset.",
    )
    domain: Optional[Int] = Field(None, description='Domain of the PTP network.')
    global_priority: Optional[Int] = Field(
        None,
        alias='globalPriority',
        description='Global priority of the clock (the first priority).',
    )
    gm_clock_id: Optional[String] = Field(
        None,
        alias='gmClockId',
        description='Unique identifier of the grandmaster clock.',
    )
    parent_clock_id: Optional[String] = Field(
        None,
        alias='parentClockId',
        description='Unique identifier of the parent clock.',
    )
    ptp_port_state: Optional[String] = Field(
        None, alias='ptpPortState', description='The port state of the device.'
    )
    ptp_profile: Optional[String] = Field(
        None, alias='ptpProfile', description='PTP profile used (e.g., ITU-T G.8275.1).'
    )
    time_recovery_status: Optional[String] = Field(
        None,
        alias='timeRecoveryStatus',
        description='Indicates the current state of the time recovery process. Time recovery is the process of adjusting\nthe local clock to synchronize with a more accurate reference clock.',
    )
    user_priority: Optional[Int] = Field(
        None,
        alias='userPriority',
        description='User defined value of the second priority.',
    )
    typename__: Optional[Literal['PtpDeviceDetails']] = Field(
        'PtpDeviceDetails', alias='__typename'
    )


class PtpDeviceEdge(BaseModel):
    """
    Grouped PtpDevice object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    node: Optional[PtpDevice] = Field(
        None, description='The associated PtpDevice object.'
    )
    typename__: Optional[Literal['PtpDeviceEdge']] = Field(
        'PtpDeviceEdge', alias='__typename'
    )


class PtpDiffSynce(Node):
    """
    A Ptp node that uses a different upstream path in SyncE topology
    """

    id: ID = Field(..., description='Ptp node id')
    ptp_upstream_interface: Optional[ID] = Field(
        None, alias='ptpUpstreamInterface', description="Ptp node's upstream interface"
    )
    ptp_upstream_interface_name: Optional[String] = Field(
        None,
        alias='ptpUpstreamInterfaceName',
        description="Ptp node's upstream interface name",
    )
    ptp_upstream_interface_status: Optional[String] = Field(
        None,
        alias='ptpUpstreamInterfaceStatus',
        description="Ptp node's upstream interface status",
    )
    synce_id: Optional[ID] = Field(
        None,
        alias='synceId',
        description='SyncE node id. This is the same device as identified',
    )
    synce_upstream_interface_name: Optional[String] = Field(
        None,
        alias='synceUpstreamInterfaceName',
        description="Synce node's upstream interface name",
    )
    typename__: Optional[Literal['PtpDiffSynce']] = Field(
        'PtpDiffSynce', alias='__typename'
    )


class PtpDiffSynceConnection(BaseModel):
    """
    Grouped list of PtpDiffSynceDevice objects and pagination metadata.
    """

    edges: Optional[List[Optional[PtpDiffSynceEdge]]] = Field(
        None, description='List of PtpDiffSynce objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['PtpDiffSynceConnection']] = Field(
        'PtpDiffSynceConnection', alias='__typename'
    )


class PtpDiffSynceEdge(BaseModel):
    """
    Grouped PtpDiffSynceDevice object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    node: Optional[PtpDiffSynce] = Field(
        None, description='The associated PtpDiffSynce object.'
    )
    typename__: Optional[Literal['PtpDiffSynceEdge']] = Field(
        'PtpDiffSynceEdge', alias='__typename'
    )


class PtpInterface(Node):
    """
    Port attached to the ptp device.
    """

    details: Optional[PtpInterfaceDetails] = Field(
        None, description='Interface details specific to PTP (Precision Time Protocol).'
    )
    id: ID = Field(..., description='Unique identifier of the object.')
    name: String = Field(..., description='Human readable name of the network port.')
    ptp_device: Optional[PtpDevice] = Field(
        None, alias='ptpDevice', description='Device that owns this interface.'
    )
    ptp_links: PtpLinkConnection = Field(
        ...,
        alias='ptpLinks',
        description='List of links connected to remote ptp devices.',
    )
    status: NodeStatus = Field(
        ...,
        description="Status of the interface from the view of the synced topology ('ok' or 'unknown').",
    )
    typename__: Optional[Literal['PtpInterface']] = Field(
        'PtpInterface', alias='__typename'
    )


class PtpInterfaceConnection(BaseModel):
    """
    Grouped list of PtpInterface objects and pagination metadata.
    """

    edges: Optional[List[Optional[PtpInterfaceEdge]]] = Field(
        None, description='List of PtpInterface objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['PtpInterfaceConnection']] = Field(
        'PtpInterfaceConnection', alias='__typename'
    )


class PtpInterfaceDetails(BaseModel):
    """
    PTP interface details.
    """

    admin_oper_status: String = Field(
        ...,
        alias='adminOperStatus',
        description="Administrative/operational status of the interface (e.g. 'up/up', 'up/down').",
    )
    ptp_status: String = Field(
        ...,
        alias='ptpStatus',
        description="State of the PTP process on the interface (e.g. 'master', 'slave', 'disabled', 'passive', 'unknown').",
    )
    ptsf_unusable: String = Field(
        ...,
        alias='ptsfUnusable',
        description='Unusable packet timing signal received by the slave, for example, where the packet delay variation is excessive,\nresulting in the slave being unable to meet the output clock performance requirements.',
    )
    typename__: Optional[Literal['PtpInterfaceDetails']] = Field(
        'PtpInterfaceDetails', alias='__typename'
    )


class PtpInterfaceEdge(BaseModel):
    """
    Grouped PtpInterface object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    node: Optional[PtpInterface] = Field(
        None, description='The associated PtpInterface object.'
    )
    typename__: Optional[Literal['PtpInterfaceEdge']] = Field(
        'PtpInterfaceEdge', alias='__typename'
    )


class PtpLinkConnection(BaseModel):
    """
    Grouped list of PtpLinks objects and pagination metadata.
    """

    edges: Optional[List[Optional[PtpLinkEdge]]] = Field(
        None, description='List of PtpInterface objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['PtpLinkConnection']] = Field(
        'PtpLinkConnection', alias='__typename'
    )


class PtpLinkEdge(BaseModel):
    """
    Grouped PtpLink object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    link: Optional[ID] = Field(
        None,
        description='Identifier of the link that connects this interface to the interface on the remote device',
    )
    node: Optional[PtpInterface] = Field(
        None, description='The associated PtpInterface object.'
    )
    typename__: Optional[Literal['PtpLinkEdge']] = Field(
        'PtpLinkEdge', alias='__typename'
    )


class PtpPath(BaseModel):
    """
    Computed path from source to destination PTP clock device.
    """

    complete: Boolean = Field(
        ...,
        description='True if path is complete - the last element in the path represents GM clock, False otherwise.',
    )
    nodes: Optional[List[ID]] = Field(
        None,
        description='Ordered list of node identifiers that compose path from source clock to destination clock.',
    )
    typename__: Optional[Literal['PtpPath']] = Field('PtpPath', alias='__typename')


class RefreshCoordinatesResponse(BaseModel):
    """
    Response containing a list of nodes with refreshed coordinates.
    """

    nodes: List[NodeCoordinates] = Field(
        ..., description='List of refreshed nodes with their new coordinates.'
    )
    typename__: Optional[Literal['RefreshCoordinatesResponse']] = Field(
        'RefreshCoordinatesResponse', alias='__typename'
    )


class RoutingPath(BaseModel):
    """
    Computed routing path from source to destination device.
    """

    nodes: List[NodeInfo] = Field(
        ...,
        description='Ordered list of nodes that compose path from source to destination device.',
    )
    weight: Int = Field(..., description='Total weight of the path.')
    typename__: Optional[Literal['RoutingPath']] = Field(
        'RoutingPath', alias='__typename'
    )


class SyncResponse(BaseModel):
    """
    Response from the sync query that contains information about synced devices from the network to topology.
    """

    devices_missing_in_inventory: Optional[List[Optional[String]]] = Field(
        None,
        alias='devicesMissingInInventory',
        description='List of devices that are installed in UniConfig but are missing their metadata in DeviceMetadata collection in the\ndatabase.',
    )
    devices_missing_in_uniconfig: Optional[List[Optional[String]]] = Field(
        None,
        alias='devicesMissingInUniconfig',
        description='List of devices that are not installed in UniConfig.',
    )
    labels: List[String] = Field(
        ...,
        description='List of string labels that are used for grouping of synced devices.\nList content should be the same as the list of labels in the input of the sync query.',
    )
    loaded_devices: JSON = Field(
        ...,
        alias='loadedDevices',
        description='Dictionary of devices and neighbors that are successfully synced from network to target topology.\nJSON format:\n{\n  "R1": [\n    {\n      "from_interface": "GigabitEthernet0/0/0/0",\n      "to_interface": "GigabitEthernet0/0/0/0",\n      "to_device": "R7"\n    },\n    {\n      "from_interface": "GigabitEthernet0/0/0/1",\n      "to_interface": "GigabitEthernet0/0/0/1",\n      "to_device": "R2"\n    }\n  ],\n  "R2": [\n    {\n      "from_interface": "GigabitEthernet0/0/0/0",\n      "to_interface": "GigabitEthernet0/0/0/0",\n      "to_device": "R3"\n    }\n  ]\n}',
    )
    typename__: Optional[Literal['SyncResponse']] = Field(
        'SyncResponse', alias='__typename'
    )


class SynceDevice(Node):
    """
    Representation of the device in the synce topology.
    """

    coordinates: Coordinates = Field(
        ..., description='Coordinates of the device node on the graph.'
    )
    details: SynceDeviceDetails = Field(..., description='Details of the device.')
    id: ID = Field(..., description='Unique identifier of the object.')
    labels: Optional[List[String]] = Field(
        None,
        description='List of strings that can be used for grouping of synced devices.',
    )
    name: String = Field(..., description='Human readable name of the device.')
    status: NodeStatus = Field(
        ..., description='Status of the device from the view of the synced topology.'
    )
    synce_interfaces: SynceInterfaceConnection = Field(
        ...,
        alias='synceInterfaces',
        description='List of ports that are present on the device.',
    )
    typename__: Optional[Literal['SynceDevice']] = Field(
        'SynceDevice', alias='__typename'
    )


class SynceDeviceConnection(BaseModel):
    """
    Grouped list of SynceDevice objects and pagination metadata.
    """

    edges: Optional[List[Optional[SynceDeviceEdge]]] = Field(
        None, description='List of SynceDevice objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['SynceDeviceConnection']] = Field(
        'SynceDeviceConnection', alias='__typename'
    )


class SynceDeviceDetails(BaseModel):
    """
    Details specific to SyncE (Synchronous Ethernet).
    """

    selected_for_use: Optional[String] = Field(
        None,
        alias='selectedForUse',
        description='Identifier of the reference (for example, source interface) that is used to synchronize the clock.',
    )
    typename__: Optional[Literal['SynceDeviceDetails']] = Field(
        'SynceDeviceDetails', alias='__typename'
    )


class SynceDeviceEdge(BaseModel):
    """
    Grouped SynceDevice object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    node: Optional[SynceDevice] = Field(
        None, description='The associated SynceDevice object.'
    )
    typename__: Optional[Literal['SynceDeviceEdge']] = Field(
        'SynceDeviceEdge', alias='__typename'
    )


class SynceInterface(Node):
    """
    Port attached to the SyncE device.
    """

    details: Optional[SynceInterfaceDetails] = Field(
        None, description='Interface details specific to SyncE operation.'
    )
    id: ID = Field(..., description='Unique identifier of the object.')
    name: String = Field(..., description='Human readable name of the network port.')
    status: NodeStatus = Field(
        ...,
        description="Status of the interface from the view of the synced topology ('ok' or 'unknown').",
    )
    synce_device: Optional[SynceDevice] = Field(
        None, alias='synceDevice', description='Device that owns this interface.'
    )
    synce_links: Optional[SynceLinkConnection] = Field(
        None, alias='synceLinks', description='Link to connected remote synce device.'
    )
    typename__: Optional[Literal['SynceInterface']] = Field(
        'SynceInterface', alias='__typename'
    )


class SynceInterfaceConnection(BaseModel):
    """
    Grouped list of SynceInterface objects and pagination metadata.
    """

    edges: Optional[List[Optional[SynceInterfaceEdge]]] = Field(
        None, description='List of SynceInterface objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['SynceInterfaceConnection']] = Field(
        'SynceInterfaceConnection', alias='__typename'
    )


class SynceInterfaceDetails(BaseModel):
    """
    Details specific to SyncE (Synchronous Ethernet).
    """

    not_qualified_due_to: Optional[String] = Field(
        None,
        alias='notQualifiedDueTo',
        description="Information about why the interface is not qualified for SyncE synchronization\n(set to 'unknown' if the interface is qualified).",
    )
    not_selected_due_to: Optional[String] = Field(
        None,
        alias='notSelectedDueTo',
        description="Information about why the interface is not selected for SyncE synchronization\n(set to 'unknown' if the interface is selected).",
    )
    qualified_for_use: Optional[String] = Field(
        None,
        alias='qualifiedForUse',
        description='Statement of whether the interface is qualified for SyncE synchronization.',
    )
    rx_quality_level: Optional[String] = Field(
        None,
        alias='rxQualityLevel',
        description="Quality of the received SyncE signal (for example, 'DNU' or 'PRC').",
    )
    synce_enabled: Optional[Boolean] = Field(
        None, alias='synceEnabled', description='Configured SyncE on the port.'
    )
    typename__: Optional[Literal['SynceInterfaceDetails']] = Field(
        'SynceInterfaceDetails', alias='__typename'
    )


class SynceInterfaceEdge(BaseModel):
    """
    Grouped SynceInterface object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    node: Optional[SynceInterface] = Field(
        None, description='The associated SynceInterface object.'
    )
    typename__: Optional[Literal['SynceInterfaceEdge']] = Field(
        'SynceInterfaceEdge', alias='__typename'
    )


class SynceLinkConnection(BaseModel):
    """
    Grouped list of SynceLinks objects and pagination metadata.
    """

    edges: Optional[List[Optional[SynceLinkEdge]]] = Field(
        None, description='List of SynceInterface objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['SynceLinkConnection']] = Field(
        'SynceLinkConnection', alias='__typename'
    )


class SynceLinkEdge(BaseModel):
    """
    Grouped SynceLink object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    link: Optional[ID] = Field(
        None,
        description='Identifier of the link that connects this interface to the interface on the remote device',
    )
    node: Optional[SynceInterface] = Field(
        None, description='The associated SynceInterface object.'
    )
    typename__: Optional[Literal['SynceLinkEdge']] = Field(
        'SynceLinkEdge', alias='__typename'
    )


class SyncePath(BaseModel):
    """
    Computed path from source to destination SYNCE device.
    """

    complete: Boolean = Field(
        ...,
        description='True if path is complete - the last element in the path represents GM, False otherwise.',
    )
    nodes: Optional[List[ID]] = Field(
        None,
        description='Ordered list of node identifiers that compose path from source device to destination device.',
    )
    typename__: Optional[Literal['SyncePath']] = Field('SyncePath', alias='__typename')


class TopologyDevice(BaseModel):
    """
    Topology and device identifier of a device.
    """

    device_id: ID = Field(
        ..., alias='deviceId', description='Topology-specific device identifier.'
    )
    topology_id: TopologyType = Field(
        ...,
        alias='topologyId',
        description='Identifier of the topology in which device is present.',
    )
    typename__: Optional[Literal['TopologyDevice']] = Field(
        'TopologyDevice', alias='__typename'
    )


class TopologyOverlayDevice(BaseModel):
    id: ID = Field(..., description='Unique identifier of the object.')
    name: String = Field(..., description='Device name.')
    second_topology_id: Optional[ID] = Field(
        None,
        alias='secondTopologyId',
        description='Document device ID from the second topology (can be null).',
    )
    topology_overlay_interfaces: TopologyOverlayInterfaceConnection = Field(
        ...,
        alias='topologyOverlayInterfaces',
        description='List of ports that are present on the device.',
    )
    typename__: Optional[Literal['TopologyOverlayDevice']] = Field(
        'TopologyOverlayDevice', alias='__typename'
    )


class TopologyOverlayDeviceConnection(BaseModel):
    """
    Grouped list of TopologyOverlayDevice objects and pagination metadata.
    """

    edges: Optional[List[Optional[TopologyOverlayDeviceEdge]]] = Field(
        None, description='List of TopologyOverlayDeviceEdge objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['TopologyOverlayDeviceConnection']] = Field(
        'TopologyOverlayDeviceConnection', alias='__typename'
    )


class TopologyOverlayDeviceEdge(BaseModel):
    """
    Grouped TopologyOverlayDeviceEdge object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    node: Optional[TopologyOverlayDevice] = Field(
        None, description='The associated TopologyOverlayDevice object.'
    )
    typename__: Optional[Literal['TopologyOverlayDeviceEdge']] = Field(
        'TopologyOverlayDeviceEdge', alias='__typename'
    )


class TopologyOverlayInterface(BaseModel):
    id: ID = Field(..., description='Document interface ID from the first topology')
    name: String = Field(..., description='Interface name.')
    second_topology_id: Optional[ID] = Field(
        None,
        alias='secondTopologyId',
        description='Document device ID from the second topology (can be null).',
    )
    topology_overlay_device: Optional[TopologyOverlayDevice] = Field(
        None,
        alias='topologyOverlayDevice',
        description='Topology overlay device that owns this interface.',
    )
    topology_overlay_links: Optional[TopologyOverlayLinkConnection] = Field(
        None,
        alias='topologyOverlayLinks',
        description='Topology overlay neighbor interface',
    )
    typename__: Optional[Literal['TopologyOverlayInterface']] = Field(
        'TopologyOverlayInterface', alias='__typename'
    )


class TopologyOverlayInterfaceConnection(BaseModel):
    """
    Grouped list of TopologyOverlayInterface objects and pagination metadata.
    """

    edges: Optional[List[Optional[TopologyOverlayInterfaceEdge]]] = Field(
        None, description='List of TopologyOverlayInterface objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['TopologyOverlayInterfaceConnection']] = Field(
        'TopologyOverlayInterfaceConnection', alias='__typename'
    )


class TopologyOverlayInterfaceEdge(BaseModel):
    """
    Grouped TopologyOverlayInterface object and associated cursor used by pagination.
    """

    cursor: String = Field(..., description='Pagination cursor for this edge.')
    node: Optional[TopologyOverlayInterface] = Field(
        None, description='The associated TopologyOverlayInterface object.'
    )
    typename__: Optional[Literal['TopologyOverlayInterfaceEdge']] = Field(
        'TopologyOverlayInterfaceEdge', alias='__typename'
    )


class TopologyOverlayLinkConnection(BaseModel):
    """
    Grouped list of TopologyOverlayLinks objects and pagination metadata.
    """

    edges: Optional[List[Optional[TopologyOverlayLinkEdge]]] = Field(
        None, description='List of TopologyOverlayInterface objects.'
    )
    page_info: PageInfo = Field(
        ..., alias='pageInfo', description='Pagination metadata.'
    )
    typename__: Optional[Literal['TopologyOverlayLinkConnection']] = Field(
        'TopologyOverlayLinkConnection', alias='__typename'
    )


class TopologyOverlayLinkEdge(BaseModel):
    cursor: String = Field(..., description='Pagination cursor for this edge.')
    link: Optional[TopologyOverlayLinkIds] = Field(
        None,
        description='Identifier of the link that connects this interface to the interface on the remote device',
    )
    node: Optional[TopologyOverlayInterface] = Field(
        None, description='The associated TopologyOverlayInterface object.'
    )
    typename__: Optional[Literal['TopologyOverlayLinkEdge']] = Field(
        'TopologyOverlayLinkEdge', alias='__typename'
    )


class TopologyOverlayLinkIds(BaseModel):
    first_topology_link_id: ID = Field(
        ...,
        alias='firstTopologyLinkId',
        description='Identifier of the link that connects this interface to the interface on the remote device on the first topology.',
    )
    second_topology_link_id: Optional[ID] = Field(
        None,
        alias='secondTopologyLinkId',
        description='Identifier of the link that connects this interface to the interface on the remote device on the second topology.',
    )
    typename__: Optional[Literal['TopologyOverlayLinkIds']] = Field(
        'TopologyOverlayLinkIds', alias='__typename'
    )


class TopologyResponse(BaseModel):
    """
    Response from the topologyDiff query that contains diff between two databases.
    """

    diff_data: Optional[JSON] = Field(
        None,
        alias='diffData',
        description='Created diff between two databases. Format of the output JSON (\'data\' represents database document):\n{\n    "added": {"PhyDevice": [{data}], "PhyInterface": [], ...},\n    "deleted": {"PhyDevice": [{data}], "PhyInterface": [], ...},\n    "changed": {"PhyDevice": [{"new": {data}, "old"}: {data}], "PhyInterface": [{"new": {data}, "old": {data}], ...}\n}',
    )
    typename__: Optional[Literal['TopologyResponse']] = Field(
        'TopologyResponse', alias='__typename'
    )


class CoordinatesInput(BaseModel):
    """
    Input of the updateCoordinates mutation that contains information about updated coordinates of a node.
    """

    node_name: String = Field(
        ..., alias='nodeName', description='Name of the node in the topology.'
    )
    node_type: CoordinatesNodeType = Field(
        ..., alias='nodeType', description='Type of the node in the topology.'
    )
    protocol_type: Optional[BgpLsProtocolType] = Field(
        None,
        alias='protocolType',
        description='Type of protocol (In case of network devices, necessary in case of NETWORK nodeType)',
    )
    x: Float = Field(
        ..., description='Updated horizontal coordinate of the node on the graph.'
    )
    y: Float = Field(
        ..., description='Updated vertical coordinate of the node on the graph.'
    )
    typename__: Optional[Literal['CoordinatesInput']] = Field(
        'CoordinatesInput', alias='__typename'
    )


class DeviceMetadataFilter(BaseModel):
    """
    Filter for Metadata device type based on device name, or other attributes.
    """

    device_name: Optional[String] = Field(
        None, alias='deviceName', description='Regex of device name.'
    )
    polygon: Optional[List[List[List[Float]]]] = Field(
        None,
        description='A GeoJSON Polygon shape used for filtering devices based on their location in this area.\n\nThe GeoJSON Polygon consists of a series of closed LineString objects (ring-like).\nThese Linear Ring objects consist of four or more coordinate pairs with the first and last coordinate\npair being equal. Coordinate pairs of a Polygon are an array of linear ring coordinate arrays.\nThe first element in the array represents the exterior ring.\nAny subsequent elements represent interior rings (holes within the surface).\n\nThe orientation of the first linear ring is crucial: the right-hand-rule is applied, so that the area to the left\nof the path of the linear ring (when walking on the surface of the Earth) is considered to be the “interior”\nof the polygon. All other linear rings must be contained within this interior.\n\nExample with a hole:\n[\n    [\n        [100.0, 0.0],\n        [101.0, 0.0],\n        [101.0, 1.0],\n        [100.0, 1.0],\n        [100.0, 0.0]\n    ],\n    [\n        [100.8, 0.8],\n        [100.8, 0.2],\n        [100.2, 0.2],\n        [100.2, 0.8],\n        [100.8, 0.8]\n    ]\n]',
    )
    topology_type: Optional[TopologyType] = Field(
        None,
        alias='topologyType',
        description='Topology in which device must be present.',
    )
    typename__: Optional[Literal['DeviceMetadataFilter']] = Field(
        'DeviceMetadataFilter', alias='__typename'
    )


class MplsDeviceFilter(BaseModel):
    """
    Filter for MplsDevice type based on device label and device name.
    """

    label: Optional[String] = Field(None, description='Device label.')
    name: Optional[String] = Field(None, description='Regex of device name.')
    typename__: Optional[Literal['MplsDeviceFilter']] = Field(
        'MplsDeviceFilter', alias='__typename'
    )


class MplsInterfaceFilter(BaseModel):
    """
    Filter for MplsInterface type based on the current interface status and name of the device.
    """

    name: Optional[String] = Field(None, description='Regex of interface name.')
    status: Optional[NodeStatus] = Field(
        None,
        description='Status of the interface from the view of the synced topology.',
    )
    typename__: Optional[Literal['MplsInterfaceFilter']] = Field(
        'MplsInterfaceFilter', alias='__typename'
    )


class NetDeviceFilter(BaseModel):
    """
    Filter for NetDevice type based on router identifier and area identifier.
    """

    ospf_area_id: Optional[String] = Field(
        None,
        alias='ospfAreaId',
        description='OSPF area identifier formatted as IPv4 address (for example, 0.0.0.0 represents area 0).',
    )
    router_id: Optional[String] = Field(
        None,
        alias='routerId',
        description='Regex of router identifier of the routing entity (usually IPv4 address).',
    )
    typename__: Optional[Literal['NetDeviceFilter']] = Field(
        'NetDeviceFilter', alias='__typename'
    )


class NetInterfaceFilter(BaseModel):
    """
    Filter for NetInterface type based on the configured IP address.
    """

    ip_address: Optional[String] = Field(
        None,
        alias='ipAddress',
        description='Regex of IP address configured on the interface.',
    )
    typename__: Optional[Literal['NetInterfaceFilter']] = Field(
        'NetInterfaceFilter', alias='__typename'
    )


class NetNetworkFilter(BaseModel):
    """
    Filter for NetNetwork type based on the subnet and route type.
    """

    ospf_route_type: Optional[Int] = Field(
        None, alias='ospfRouteType', description='Type of the OSPF network (LSA type).'
    )
    subnet: Optional[String] = Field(
        None,
        description='Regex of network address including prefix length (e.g. 10.0.0.0/24)',
    )
    typename__: Optional[Literal['NetNetworkFilter']] = Field(
        'NetNetworkFilter', alias='__typename'
    )


class PhyDeviceFilter(BaseModel):
    """
    Filter for PhyDevice type based on device label and device name.
    """

    label: Optional[String] = Field(None, description='Device label.')
    name: Optional[String] = Field(None, description='Regex of device name.')
    typename__: Optional[Literal['PhyDeviceFilter']] = Field(
        'PhyDeviceFilter', alias='__typename'
    )


class PhyInterfaceFilter(BaseModel):
    """
    Filter for PhyInterface type based on the current interface status and name of the device.
    """

    name: Optional[String] = Field(None, description='Regex of interface name.')
    status: Optional[String] = Field(
        None,
        description='Status of the interface from the view of the synced topology.',
    )
    typename__: Optional[Literal['PhyInterfaceFilter']] = Field(
        'PhyInterfaceFilter', alias='__typename'
    )


class PtpDeviceFilter(BaseModel):
    """
    Filter for PtpDevice type based on device label and device name.
    """

    clock_accuracy: Optional[String] = Field(
        None,
        alias='clockAccuracy',
        description='Regex: clock accuracy to primary reference.',
    )
    clock_class: Optional[Int] = Field(
        None, alias='clockClass', description='Measure of clock traceability.'
    )
    clock_id: Optional[String] = Field(
        None, alias='clockId', description='Regex: Unique identifier of the clock.'
    )
    clock_type: Optional[String] = Field(
        None,
        alias='clockType',
        description='Regex: Type of clock (e.g., ordinary, master).',
    )
    clock_variance: Optional[String] = Field(
        None, alias='clockVariance', description='Regex: measure of clock precision.'
    )
    domain: Optional[Int] = Field(None, description='Domain of the PTP network.')
    label: Optional[String] = Field(None, description='Device label.')
    name: Optional[String] = Field(None, description='Regex of device name.')
    ptp_profile: Optional[String] = Field(
        None, alias='ptpProfile', description='PTP profile used (e.g., ITU-T G.8275.1).'
    )
    time_recovery_status: Optional[String] = Field(
        None,
        alias='timeRecoveryStatus',
        description='Regex: indicates the current state of the time recovery process.',
    )
    typename__: Optional[Literal['PtpDeviceFilter']] = Field(
        'PtpDeviceFilter', alias='__typename'
    )


class PtpInterfaceFilter(BaseModel):
    """
    Filter for PtpInterface type based on the current interface status and name of the device.
    """

    admin_oper_status: Optional[String] = Field(
        None,
        alias='adminOperStatus',
        description="Regex of administrative/operational status on the interface (e.g. 'up/up', 'up/down').",
    )
    name: Optional[String] = Field(None, description='Regex of interface name.')
    ptp_status: Optional[String] = Field(
        None,
        alias='ptpStatus',
        description='Regex of the PTP process status on the interface.',
    )
    ptsf_unusable: Optional[String] = Field(
        None,
        alias='ptsfUnusable',
        description='Regex of unusable packet timing signal received by the slave.',
    )
    status: Optional[NodeStatus] = Field(
        None,
        description='Status of the interface from the view of the synced topology.',
    )
    typename__: Optional[Literal['PtpInterfaceFilter']] = Field(
        'PtpInterfaceFilter', alias='__typename'
    )


class SynceDeviceFilter(BaseModel):
    """
    Filter for SynceDevice type based on device label and device name.
    """

    label: Optional[String] = Field(None, description='Device label.')
    name: Optional[String] = Field(None, description='Regex of device name.')
    selected_for_use: Optional[String] = Field(
        None,
        alias='selectedForUse',
        description='Regex: identifier of the reference (for example, source interface) that is used to synchronize the clock.',
    )
    typename__: Optional[Literal['SynceDeviceFilter']] = Field(
        'SynceDeviceFilter', alias='__typename'
    )


class SynceInterfaceFilter(BaseModel):
    """
    Filter for SynceInterface type based on the current interface status and name of the device.
    """

    name: Optional[String] = Field(None, description='Regex of interface name.')
    not_qualified_due_to: Optional[String] = Field(
        None,
        alias='notQualifiedDueTo',
        description='Regex: Information about why the interface is not qualified for SyncE synchronization.',
    )
    not_selected_due_to: Optional[String] = Field(
        None,
        alias='notSelectedDueTo',
        description='Regex: Information about why the interface is not selected for SyncE synchronization.',
    )
    qualified_for_use: Optional[String] = Field(
        None,
        alias='qualifiedForUse',
        description='Regex: Statement of whether the interface is qualified for SyncE synchronization.',
    )
    rx_quality_level: Optional[String] = Field(
        None,
        alias='rxQualityLevel',
        description="Regex: Quality of the received SyncE signal (for example, 'DNU' or 'PRC').",
    )
    status: Optional[NodeStatus] = Field(
        None,
        description='Status of the interface from the view of the synced topology.',
    )
    synce_enabled: Optional[Boolean] = Field(
        None, alias='synceEnabled', description='Configured SyncE on the port.'
    )
    typename__: Optional[Literal['SynceInterfaceFilter']] = Field(
        'SynceInterfaceFilter', alias='__typename'
    )


class TopologyOverlayDeviceFilter(BaseModel):
    """
    Filter for TopologyOverlayDevice type based on device name.
    """

    name: Optional[String] = Field(None, description='Regex of device name.')
    typename__: Optional[Literal['TopologyOverlayDeviceFilter']] = Field(
        'TopologyOverlayDeviceFilter', alias='__typename'
    )


class TopologyOverlayInterfaceFilter(BaseModel):
    """
    Filter for TopologyOverlayInterface type based on the name of the device.
    """

    name: Optional[String] = Field(None, description='Regex of interface name.')
    typename__: Optional[Literal['TopologyOverlayInterfaceFilter']] = Field(
        'TopologyOverlayInterfaceFilter', alias='__typename'
    )
