# generated by datamodel-codegen

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import ConfigDict


class Output(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    nodes: Optional[list[str]] = None
    """
    List of template names.
    """
