# generated by datamodel-codegen

from __future__ import annotations

from enum import Enum


class ModeEnum(Enum):
    """
    Subscription mode for gnmi streaming

    """

    SAMPLE = 'SAMPLE'
    ON_CHANGE = 'ON_CHANGE'
    TARGET_DEFINED = 'TARGET_DEFINED'
