# generated by datamodel-codegen

from __future__ import annotations

from enum import Enum


class ModeEnum(Enum):
    SAMPLE = 'SAMPLE'
    ON_CHANGE = 'ON_CHANGE'
    TARGET_DEFINED = 'TARGET_DEFINED'
