# generated by datamodel-codegen

from __future__ import annotations

from enum import Enum


class AdminState(Enum):
    locked = 'locked'
    unlocked = 'unlocked'
    southbound_locked = 'southbound_locked'


class ConnectionType(Enum):
    cli = 'cli'
    netconf = 'netconf'
    uniconfig_preferred_connection = 'uniconfig-preferred-connection'
    gnmi = 'gnmi'
    netconf_dryrun_connection = 'netconf-dryrun-connection'
    cli_dryrun_connection = 'cli-dryrun-connection'


class MountType(Enum):
    cli = 'cli'
    netconf = 'netconf'
    uniconfig_preferred_connection = 'uniconfig-preferred-connection'
    gnmi = 'gnmi'
    netconf_dryrun_connection = 'netconf-dryrun-connection'
    cli_dryrun_connection = 'cli-dryrun-connection'
