# generated by datamodel-codegen

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from . import AdminState


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    node_id: str = Field(..., alias='node-id')
    """
    Node identifier of CLI/NETCONF node.
    """
    admin_state: Optional[AdminState] = Field(None, alias='admin-state')
