# generated by datamodel-codegen

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field


class TargetNodes(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    node: Optional[list[str]] = None


class Input(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    connection_timeout: Optional[int] = Field(
        None, alias='connection-timeout', ge=0, le=65535
    )
    """
    Timeout for each health-check session to be established individually. Default 5 seconds.
    """
    target_nodes: Optional[TargetNodes] = Field(
        None,
        alias='target-nodes',
        title='uniconfig.manager.targetuniconfignodesfields.TargetNodes',
    )
