# generated by datamodel-codegen

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field

from . import MountType


class Output(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    nodes: Optional[list[str]] = None
    """
    List of node identifiers.
    """


class Input(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    mount_type: Optional[MountType] = Field(None, alias='mount-type')
