# generated by datamodel-codegen

from __future__ import annotations

from pydantic import ConfigDict

from .device_parent import DeviceParentSchema


class DeviceRegistration(DeviceParentSchema):
    """
    Device registration schema
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    device_name: str
    """
    The name of the device.
    """
    zone_id: str
    """
    The zone ID of the device.
    """
