# generated by datamodel-codegen

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class DeviceRemoval(BaseModel):
    """
    Device removal schema
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    device_name: str
    """
    The name of the device.
    """
