# generated by datamodel-codegen

from __future__ import annotations

from typing import Any

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field


class PerformanceMessage(BaseModel):
    """
    Schema for processed and unified performance monitoring notifications
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    deviceName: str
    """
    The name of the device.
    """
    eventTime: str = Field(
        ...,
        pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{5}-\\d{2}:\\d{2}$',
    )
    """
    The timestamp when notification arrived.
    """
    metrics: Any
    """
    The measured metrics.
    """
