# generated by datamodel-codegen

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import ConfigDict


class PerformanceMonitoringNotification(BaseModel):
    """
    Schema for performance monitoring notifications
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    node_id: Optional[str] = None
    """
    The name of the node.
    """
    identifier: Optional[str] = None
    """
    Identifier/path to data.
    """
    event_time: Optional[str] = None
    """
    The timestamp when notification arrived.
    """
    body: Optional[str] = None
    """
    The data.
    """
