# generated by datamodel-codegen

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field

from ... import logging
from . import HttpMethod


class Input(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    hidden_http_methods: Optional[list[HttpMethod]] = Field(
        None, alias='hidden-http-methods'
    )
    """
    HTTP requests (and associated HTTP responses) are not logged if request's HTTP method is set
    to one of the methods in this list.
    """


class Output(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    message: Optional[str] = None
    """
    Information message about state of operation.
    """
    status: logging.RpcStatus
