#!/usr/bin/env bash

INPUT_PATH='utils/json-schemas'
OUTPUT_PATH='frinx_api/json_schema'

uid=$(stat -c '%u' ${OUTPUT_PATH} )
gid=$(stat -c '%g' ${OUTPUT_PATH} )

rm -rf "${OUTPUT_PATH}/*"

poetry install

poetry run datamodel-codegen \
  --disable-timestamp \
  --use-field-description \
  --use-schema-description \
  --use-default \
  --field-constraints \
  --collapse-root-models \
  --use-standard-collections \
  --allow-population-by-field-name \
  --input "../../${INPUT_PATH}" \
  --input-file-type jsonschema \
  --output "${OUTPUT_PATH}" \
  --output-model-type pydantic_v2.BaseModel \
  --target-python-version 3.10 \
  --custom-file-header "# generated by datamodel-codegen"

## use default formatting
poetry run ruff --fix . || true

chown -R "${uid}:${gid}" "${OUTPUT_PATH}/"*
