#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "$DIR/../../utils/json-schemas"
API_PATH='frinx_api/json_schema/'

uid=$(stat -c '%u' ${API_PATH} )
gid=$(stat -c '%g' ${API_PATH} )

rm -rf "${API_PATH}/*"

poetry install

poetry run datamodel-codegen \
  --disable-timestamp \
  --use-field-description \
  --use-schema-description \
  --use-default \
  --field-constraints \
  --collapse-root-models \
  --use-standard-collections \
  --allow-population-by-field-name \
  --input "${DIR}/../../utils/json-schemas" \
  --input-file-type jsonschema \
  --output "${API_PATH}" \
  --output-model-type pydantic_v2.BaseModel \
  --target-python-version 3.10 \
  --custom-file-header "# generated by datamodel-codegen"

## use default formatting
poetry run ruff --fix . || true

chown -R "${uid}:${gid}" "${API_PATH}/*"
